"""
Django settings for olfati_django project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



DATABASES = {
   'default': {
       'ENGINE': os.getenv("DB_ENGINE"),
       'NAME': os.getenv("DB_DATABASE"),
       'USER': os.getenv("DB_USERNAME"),
       'PASSWORD': os.getenv("DB_PASSWORD"),
       'HOST': os.getenv("DB_HOST"),
       'PORT':  os.getenv("DB_PORT"),
    }
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ira0@ix)3pip7)de1=!e1qfa#hizidv0@g2fffm7a&h=lahrbz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["https://cartino.chbk.run","cartino.chbk.run"]
#CSRF_TRUSTED_ORIGINS = ["https://cartino.chbk.run","cartino.chbk.run"]


MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'


STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    # 'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'accounts',
    'exam',
    "core",
    "litner",
    "markethub",
    "django_celery_results",
    'django_celery_beat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'olfati_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'olfati_django.wsgi.application'

AUTH_USER_MODEL = 'accounts.UserModel'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#      'default': {
#          'ENGINE': 'django.db.backends.sqlite3',
#          'NAME': BASE_DIR / 'db.sqlite3',
#      }
#  }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# TOKEN.obtain_auth_token
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ]
}

SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('JWT',),
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
}
# تنظیمات JWT
JWT_AUTH = {
    'JWT_SECRET_KEY': SECRET_KEY,  # کلید مخفی برای امضای توکن
    'JWT_GET_USER_SECRET_KEY': None,  # تابع برای دریافت کلید مخفی کاربر (با توجه به شناسه کاربری)
    'JWT_PAYLOAD_HANDLER': 'path.to.custom_payload_handler',  # تابع برای ایجاد بسته داده‌های توکن
    'JWT_RESPONSE_PAYLOAD_HANDLER': 'path.to.custom_response_payload_handler',
    # تابع برای ایجاد پاسخ دریافتی بعد از درخواست توکن
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(weeks=24),  # مدت اعتبار توکن دسترسی
    'REFRESH_TOKEN_LIFETIME': timedelta(weeks=48),  # مدت اعتبار توکن بازیابی
}

REDIRECTURL = "https://olfati.iran.liara.run"
CALLBACKURL = 'http://{REDIRECTURL}/markethub/zarrin-pall/verify/'
MERCHANT = "7bd2714c-3674-4566-a4ff-8ec4ed9fac64"

LANGUAGE_CODE = 'fa'







# مسیر به کلید خصوصی دانلود شده
FIREBASE_ADMIN_KEY_PATH = os.path.join(BASE_DIR, 'firebase_admin_key.json')

BROKER_URL = 'redis://:Fig3GFX9dLysKjUO@services.gen3.chabokan.net:46524/0'
CELERY_RESULT_BACKEND = 'redis://:Fig3GFX9dLysKjUO@services.gen3.chabokan.net:46524/0'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Tehran'

# # CELERY SETTINGS
# CELERY_BROKER_URL = 'redis://127.0.0.1:6379'
# CELERY_ACCEPT_CONTENT = ['application/json']
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_BACKEND = 'django-db'
# CELERY_TIMEZONE = 'Asia/Tehran'

# # CELERY BEAT SCHEDULER
# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# # REDIS CACHE
# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": f"redis://127.0.0.1:6379/1",
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#         },
#     }
# }