# Generated by Django 5.2 on 2025-04-30 17:24

import utils.vlaidations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, validators=[utils.vlaidations.PhoneValidator()], verbose_name='شماره تلفن'),
        ),
    ]
