# Generated by Django 4.2.15 on 2024-08-20 17:09

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='full_name',
            field=models.CharField(max_length=35, verbose_name='نام کامل'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='melli_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=255, null=True, verbose_name='رمز عبور'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='study_field',
            field=models.CharField(max_length=50, verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='نام کاربری'),
        ),
    ]
