# Generated by Django 5.2 on 2025-04-19 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpmodel',
            name='otpCode',
        ),
        migrations.AddField(
            model_name='otpmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otpmodel',
            name='expired_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='otpmodel',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
