# Generated by Django 5.2 on 2025-05-07 16:31

import utils.vlaidations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpmodel',
            options={'verbose_name': 'کد اعتبار سنجی', 'verbose_name_plural': 'کد های اعتبار سنجی'},
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expired_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='انقضای کد'),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='تکمیل حساب'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_deleted',
            field=models.BooleanField(blank=True, editable=False, null=True, verbose_name='حذف شده یا خیر'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='melli_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, validators=[utils.vlaidations.PhoneValidator()], verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='study_field',
            field=models.CharField(blank=True, max_length=50, verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(blank=True, max_length=30, verbose_name='نام کاربری'),
        ),
    ]
