# Generated by Django 4.2.1 on 2023-06-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usermodel_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
