# Generated by Django 5.2 on 2025-04-19 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_otpmodel_otpcode_otpmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='otpmodel',
            table='otp_code',
        ),
    ]
