# Generated by Django 5.2 on 2025-05-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usermodel_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='melli_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد ملی'),
        ),
    ]
