# Generated by Django 5.2 on 2025-05-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usermodel_melli_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='نام کاربری'),
        ),
    ]
