# Generated by Django 5.2 on 2025-05-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usermodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=None, editable=False, null=True),
        ),
    ]
