# Generated by Django 5.2 on 2025-04-25 12:25

import django.db.models.deletion
import utils.vlaidations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeitnerBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box_number', models.IntegerField(choices=[(1, 'خانه ۱'), (2, 'خانه ۲'), (3, 'خانه ۳'), (4, 'خانه ۴'), (5, 'خانه ۵')], default=1, verbose_name='شماره خانه')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'باکس',
                'verbose_name_plural': 'باکس ها',
                'db_table': 'linter_box',
            },
        ),
        migrations.CreateModel(
            name='LinterFlashCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.CharField(max_length=255, verbose_name='سوال را وارد کنید')),
                ('answers_text', models.TextField(blank=True, max_length=200, null=True, verbose_name='جواب را وارد کنید')),
                ('is_active', models.BooleanField(default=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flash_cart', to='litner.leitnerbox')),
            ],
            options={
                'verbose_name': 'فلش کارت',
                'verbose_name_plural': 'فلش کارت ها',
                'db_table': 'linter_flash_cart',
            },
        ),
        migrations.CreateModel(
            name='LitnerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='media/linter_image_cover/', validators=[utils.vlaidations.validate_image_size], verbose_name='عکس کاور')),
                ('price', models.FloatField(verbose_name='قیمیت فصل')),
                ('data_created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('is_publish', models.BooleanField(default=True)),
                ('paid_users', models.ManyToManyField(blank=True, related_name='paid_litner', to=settings.AUTH_USER_MODEL, verbose_name='دسترسی کاربران')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصل ها',
                'db_table': 'linter',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='leitnerbox',
            name='linter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linter_box', to='litner.litnermodel', verbose_name='فصل'),
        ),
        migrations.CreateModel(
            name='MyLinterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=None, editable=False, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('study_field', models.CharField(max_length=100, verbose_name='رشته تحصیلی')),
                ('is_publish', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('cover_image', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='catalog_app.image')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس ها',
                'db_table': 'linter_class',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='litnermodel',
            name='myclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linter', to='litner.mylinterclass', verbose_name='کلاس مربوطه'),
        ),
        migrations.AlterUniqueTogether(
            name='leitnerbox',
            unique_together={('linter', 'box_number')},
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box_number', models.PositiveSmallIntegerField(help_text='شماره باکس')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='پاسخ کاربر')),
                ('status', models.CharField(choices=[('correct', 'صحیح'), ('wrong', 'غلط'), ('skipped', 'رد شده')], help_text='correct | wrong | skipped', max_length=10, verbose_name='وضعیت پاسخ')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linter_flash_cart', to='litner.linterflashcart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leitner_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پاسخ کاربر',
                'verbose_name_plural': 'پاسخ\u200cهای کاربران',
                'db_table': 'leitner_user_answers',
                'unique_together': {('user', 'box')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='تعداد کل سوالات')),
                ('answered_questions', models.PositiveIntegerField(default=0, verbose_name='تعداد پاسخ\u200cهای داده شده')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='تعداد پاسخ\u200cهای صحیح')),
                ('current_box_distribution', models.JSONField(default=dict, help_text='تعداد کارت\u200cها در هر خانه لایتنر', verbose_name='توزیع کارت\u200cها در خانه\u200cها')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='آخرین فعالیت')),
                ('linter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_progress', to='litner.litnermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leitner_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیشرفت کاربر',
                'verbose_name_plural': 'پیشرفت\u200cهای کاربران',
                'db_table': 'leitner_user_progress',
                'unique_together': {('user', 'linter')},
            },
        ),
    ]
