# Generated by Django 4.2.1 on 2023-05-30 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LitnerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('study_field', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(null=True, upload_to='litner_image_cover/')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LitnerQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=150)),
                ('answers_text', models.CharField(max_length=100)),
                ('litner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litner', to='litner.litnermodel')),
            ],
        ),
        migrations.CreateModel(
            name='LitnerKarNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='karname', to='litner.litnermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LitnerAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('N', 'No Answer'), ('F', 'False Answer'), ('T', 'True Answer')], max_length=1)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='litner.litnerquestionmodel')),
                ('litner_azmon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='litner_azmon', to='litner.litnerkarnamemodel')),
            ],
        ),
    ]
