# Generated by Django 5.2 on 2025-05-09 23:02

import django.db.models.deletion
import utils.vlaidations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اخرین بروزرسانی')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ حذف')),
                ('is_deleted', models.BooleanField(blank=True, editable=False, null=True, verbose_name='حذف شده یا خیر')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('cover_image', models.ImageField(null=True, upload_to='linter_season/%Y/%m/%d', validators=[utils.vlaidations.validate_image_size], verbose_name='تصویر کاور')),
                ('price', models.FloatField(verbose_name='قیمت فصل')),
                ('is_sale', models.BooleanField(default=True, help_text='قابل فروش باشد', verbose_name='قابل فروش باشد')),
                ('paid_users', models.ManyToManyField(blank=True, related_name='paid_litner', to=settings.AUTH_USER_MODEL, verbose_name='دسترسی کاربران')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصل\u200cها',
                'db_table': 'linter_model',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LinterFlashCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اخرین بروزرسانی')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ حذف')),
                ('is_deleted', models.BooleanField(blank=True, editable=False, null=True, verbose_name='حذف شده یا خیر')),
                ('question_text', models.CharField(max_length=255, verbose_name='سوال را وارد کنید')),
                ('answers_text', models.TextField(blank=True, max_length=200, null=True, verbose_name='جواب را وارد کنید')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linter_flash_cart', to='litner.lintermodel', verbose_name='فصل')),
            ],
            options={
                'verbose_name': 'فلش کارت',
                'verbose_name_plural': 'فلش کارت\u200cها',
                'db_table': 'linter_flash_cart',
            },
        ),
        migrations.CreateModel(
            name='MyLinterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اخرین بروزرسانی')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ حذف')),
                ('is_deleted', models.BooleanField(blank=True, editable=False, null=True, verbose_name='حذف شده یا خیر')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('study_field', models.CharField(max_length=100, verbose_name='رشته تحصیلی')),
                ('cover_image', models.ImageField(null=True, upload_to='linter_class/%Y/%m/%d', validators=[utils.vlaidations.validate_image_size], verbose_name='تصویر کاور')),
                ('author', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس\u200cها',
                'db_table': 'linter_class',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='lintermodel',
            name='myclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linter', to='litner.mylinterclass', verbose_name='کلاس مربوطه'),
        ),
        migrations.CreateModel(
            name='UserLinterFlashCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اخرین بروزرسانی')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ حذف')),
                ('is_deleted', models.BooleanField(blank=True, editable=False, null=True, verbose_name='حذف شده یا خیر')),
                ('box', models.PositiveSmallIntegerField(default=1, verbose_name='باکس')),
                ('flash_cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='linter_flash_cart', to='litner.linterflashcart', verbose_name='فلش کارت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_flash_cart', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فلش کارت کاربر',
                'verbose_name_plural': 'فلش کارت های کاربر',
                'db_table': 'user_linter_flash_cart',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اخرین بروزرسانی')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ حذف')),
                ('is_deleted', models.BooleanField(blank=True, editable=False, null=True, verbose_name='حذف شده یا خیر')),
                ('is_correct', models.BooleanField(blank=True, help_text='در صورت عدم پاسخ مقدار نال یا همان بی پاسخ ذخیره خواهد شد', null=True, verbose_name='پاسخ صحیح')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('flash_cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answer_flash_cart', to='litner.userlinterflashcart', verbose_name='فلش کارت')),
            ],
            options={
                'verbose_name': 'پاسخ کاربر',
                'verbose_name_plural': 'پاسخ\u200cهای کاربران',
                'db_table': 'leitner_user_answers',
            },
        ),
        migrations.CreateModel(
            name='LeitnerBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اخرین بروزرسانی')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ حذف')),
                ('is_deleted', models.BooleanField(blank=True, editable=False, null=True, verbose_name='حذف شده یا خیر')),
                ('box_number', models.IntegerField(choices=[(1, 'خانه ۱'), (2, 'خانه ۲'), (3, 'خانه ۳'), (4, 'خانه ۴'), (5, 'خانه ۵'), (6, 'خانه ۶')], default=1, verbose_name='شماره خانه')),
                ('linter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linter_box', to='litner.lintermodel', verbose_name='فصل')),
            ],
            options={
                'verbose_name': 'باکس',
                'verbose_name_plural': 'باکس\u200cها',
                'db_table': 'linter_box',
                'unique_together': {('linter', 'box_number')},
            },
        ),
    ]
