# Generated by Django 5.2 on 2025-04-25 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0004_remove_image_is_active'),
        ('litner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=None, editable=False, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField()),
                ('price', models.FloatField(verbose_name='قیمیت فصل')),
                ('data_created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('is_publish', models.BooleanField(default=True)),
                ('cover_image', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='linter_cover_image', to='catalog_app.image')),
                ('myclass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linter', to='litner.mylinterclass', verbose_name='کلاس مربوطه')),
                ('paid_users', models.ManyToManyField(blank=True, related_name='paid_litner', to=settings.AUTH_USER_MODEL, verbose_name='دسترسی کاربران')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصل ها',
                'db_table': 'linter_model',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='leitnerbox',
            name='linter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linter_box', to='litner.lintermodel', verbose_name='فصل'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='linter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_progress', to='litner.lintermodel'),
        ),
        migrations.DeleteModel(
            name='LitnerModel',
        ),
    ]
