# Generated by Django 5.2 on 2025-05-06 19:50

import utils.vlaidations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lintermodel',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='linter_season/%Y/%m/%d', validators=[utils.vlaidations.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='mylinterclass',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='linter_class/%Y/%m/%d', validators=[utils.vlaidations.validate_image_size]),
        ),
    ]
