# Generated by Django 5.2 on 2025-05-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(default=None, help_text='در صورت عدم پاسخ مقدار نال یا همان بی پاسخ ذخیره خواهد شد', null=True, verbose_name='پاسخ صحیح'),
        ),
    ]
