# Generated by Django 4.2.4 on 2023-12-01 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.vlaidations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('litner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='litnerkarnamemodel',
            options={'verbose_name': 'کارنامه', 'verbose_name_plural': 'کارنامه ها'},
        ),
        migrations.AlterModelOptions(
            name='litnermodel',
            options={'verbose_name': 'فصل', 'verbose_name_plural': 'فصل ها'},
        ),
        migrations.AlterModelOptions(
            name='litnerquestionmodel',
            options={'verbose_name': 'سوال', 'verbose_name_plural': 'سوالات'},
        ),
        migrations.AlterModelOptions(
            name='mylitnerclass',
            options={'verbose_name': 'کلاس', 'verbose_name_plural': 'کلاس ها'},
        ),
        migrations.AlterField(
            model_name='litneranswer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='صحیح بودن'),
        ),
        migrations.AlterField(
            model_name='litneranswer',
            name='karname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='litner_azmon', to='litner.litnerkarnamemodel', verbose_name='کارنامه'),
        ),
        migrations.AlterField(
            model_name='litneranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='litner.litnerquestionmodel', verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='litnerkarnamemodel',
            name='exam_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_id', to='litner.litnermodel', verbose_name='فصل'),
        ),
        migrations.AlterField(
            model_name='litnerkarnamemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='litnermodel',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='media/litner_image_cover/', validators=[utils.vlaidations.validate_image_size], verbose_name='عکس کاور'),
        ),
        migrations.AlterField(
            model_name='litnermodel',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='litnermodel',
            name='myclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litners', to='litner.mylitnerclass', verbose_name='کلاس'),
        ),
        migrations.AlterField(
            model_name='litnermodel',
            name='title',
            field=models.TextField(verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='litnerquestionmodel',
            name='answers_text',
            field=models.TextField(verbose_name='متن جواب'),
        ),
        migrations.AlterField(
            model_name='litnerquestionmodel',
            name='litner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litner', to='litner.litnermodel', verbose_name='فصل'),
        ),
        migrations.AlterField(
            model_name='litnerquestionmodel',
            name='question_text',
            field=models.TextField(verbose_name='متن سوال'),
        ),
        migrations.AlterField(
            model_name='mylitnerclass',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='mylitnerclass',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='media/classes_image_cover/', validators=[utils.vlaidations.validate_image_size], verbose_name='عکس کاور'),
        ),
        migrations.AlterField(
            model_name='mylitnerclass',
            name='study_field',
            field=models.CharField(max_length=100, verbose_name='فیلد مطالعه'),
        ),
        migrations.AlterField(
            model_name='mylitnerclass',
            name='title',
            field=models.TextField(verbose_name='عنوان'),
        ),
    ]
