# Generated by Django 5.2 on 2025-04-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litner', '0002_lintermodel_alter_leitnerbox_linter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lintermodel',
            name='data_created',
        ),
    ]
