# Generated by Django 5.2 on 2025-05-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litner', '0002_alter_useranswer_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(blank=True, help_text='در صورت عدم پاسخ مقدار نال یا همان بی پاسخ ذخیره خواهد شد', null=True, verbose_name='پاسخ صحیح'),
        ),
    ]
