# Generated by Django 5.2 on 2025-05-07 16:31

import django.db.models.deletion
import utils.vlaidations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litner', '0002_alter_lintermodel_cover_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leitnerbox',
            options={'verbose_name': 'باکس', 'verbose_name_plural': 'باکس\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='linterflashcart',
            options={'verbose_name': 'فلش کارت', 'verbose_name_plural': 'فلش کارت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='lintermodel',
            options={'ordering': ('-created_at',), 'verbose_name': 'فصل', 'verbose_name_plural': 'فصل\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='mylinterclass',
            options={'ordering': ('-created_at',), 'verbose_name': 'کلاس', 'verbose_name_plural': 'کلاس\u200cها'},
        ),
        migrations.AlterField(
            model_name='leitnerbox',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AlterField(
            model_name='leitnerbox',
            name='is_deleted',
            field=models.BooleanField(blank=True, editable=False, null=True, verbose_name='حذف شده یا خیر'),
        ),
        migrations.AlterField(
            model_name='leitnerbox',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='اخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='linterflashcart',
            name='box',
            field=models.PositiveIntegerField(default=1, verbose_name='باکس'),
        ),
        migrations.AlterField(
            model_name='linterflashcart',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AlterField(
            model_name='linterflashcart',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='linterflashcart',
            name='is_deleted',
            field=models.BooleanField(blank=True, editable=False, null=True, verbose_name='حذف شده یا خیر'),
        ),
        migrations.AlterField(
            model_name='linterflashcart',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linter_flash_cart', to='litner.lintermodel', verbose_name='فصل'),
        ),
        migrations.AlterField(
            model_name='linterflashcart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='اخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='lintermodel',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='linter_season/%Y/%m/%d', validators=[utils.vlaidations.validate_image_size], verbose_name='تصویر کاور'),
        ),
        migrations.AlterField(
            model_name='lintermodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AlterField(
            model_name='lintermodel',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='lintermodel',
            name='is_deleted',
            field=models.BooleanField(blank=True, editable=False, null=True, verbose_name='حذف شده یا خیر'),
        ),
        migrations.AlterField(
            model_name='lintermodel',
            name='is_sale',
            field=models.BooleanField(default=True, help_text='قابل فروش باشد', verbose_name='قابل فروش باشد'),
        ),
        migrations.AlterField(
            model_name='lintermodel',
            name='price',
            field=models.FloatField(verbose_name='قیمت فصل'),
        ),
        migrations.AlterField(
            model_name='lintermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='اخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='mylinterclass',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='linter_class/%Y/%m/%d', validators=[utils.vlaidations.validate_image_size], verbose_name='تصویر کاور'),
        ),
        migrations.AlterField(
            model_name='mylinterclass',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AlterField(
            model_name='mylinterclass',
            name='is_deleted',
            field=models.BooleanField(blank=True, editable=False, null=True, verbose_name='حذف شده یا خیر'),
        ),
        migrations.AlterField(
            model_name='mylinterclass',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='اخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='flash_cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linter_flash_cart', to='litner.linterflashcart', verbose_name='فلش کارت'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(blank=True, help_text='در صورت عدم پاسخ مقدار نال یا همان بی پاسخ ذخیره خواهد شد', null=True, verbose_name='پاسخ صحیح'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='is_deleted',
            field=models.BooleanField(blank=True, editable=False, null=True, verbose_name='حذف شده یا خیر'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='اخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='is_deleted',
            field=models.BooleanField(blank=True, editable=False, null=True, verbose_name='حذف شده یا خیر'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='linter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='litner.lintermodel', verbose_name='فصل'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='اخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leitner_progress', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
