# Generated by Django 4.2.4 on 2023-12-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litner', '0002_alter_litnerkarnamemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litnerquestionmodel',
            name='answers_text',
            field=models.TextField(verbose_name='جواب را وارد کنید'),
        ),
        migrations.AlterField(
            model_name='litnerquestionmodel',
            name='question_text',
            field=models.TextField(verbose_name='سوال را وارد کنید'),
        ),
        migrations.AlterField(
            model_name='mylitnerclass',
            name='study_field',
            field=models.CharField(max_length=100, verbose_name='رشته تحصیلی'),
        ),
    ]
