# Generated by Django 5.2 on 2025-05-08 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litner', '0003_alter_leitnerbox_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linterflashcart',
            name='box',
        ),
        migrations.CreateModel(
            name='UserLinterFlashCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اخرین بروزرسانی')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ حذف')),
                ('is_deleted', models.BooleanField(blank=True, editable=False, null=True, verbose_name='حذف شده یا خیر')),
                ('box', models.PositiveSmallIntegerField(default=1)),
                ('flash_cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='linter_flash_cart', to='litner.linterflashcart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_flash_cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فلش کارت کاربر',
                'verbose_name_plural': 'فلش کارت های کاربر',
                'db_table': 'user_linter_flash_cart',
            },
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='flash_cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answer_flash_cart', to='litner.userlinterflashcart', verbose_name='فلش کارت'),
        ),
    ]
