# Generated by Django 5.2 on 2025-04-25 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litner', '0003_remove_lintermodel_data_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leitnerbox',
            name='is_active',
        ),
    ]
