# Generated by Django 4.2.4 on 2023-12-02 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('litner', '0003_alter_litnerquestionmodel_answers_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='litnermodel',
            name='paid_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='paid_litner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='litnermodel',
            name='price',
            field=models.SmallIntegerField(null=True),
        ),
    ]
