# Generated by Django 4.2.4 on 2023-12-03 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('litner', '0004_litnermodel_paid_users_litnermodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='litnermodel',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='litnermodel',
            name='myclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litners', to='litner.mylitnerclass', verbose_name='کلاس مربوطه'),
        ),
        migrations.AlterField(
            model_name='litnermodel',
            name='paid_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='paid_litner', to=settings.AUTH_USER_MODEL, verbose_name='دسترسی کاربران'),
        ),
        migrations.AlterField(
            model_name='litnermodel',
            name='price',
            field=models.SmallIntegerField(null=True, verbose_name='قیمیت فصل'),
        ),
    ]
