# Generated by Django 5.2 on 2025-04-25 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litner', '0006_alter_leitnerbox_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lintermodel',
            name='is_publish',
        ),
    ]
