# Generated by Django 5.2 on 2025-04-25 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litner', '0007_remove_lintermodel_is_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylinterclass',
            name='is_publish',
        ),
    ]
