# Generated by Django 5.2 on 2025-04-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litner', '0008_remove_mylinterclass_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='lintermodel',
            name='is_sale',
            field=models.BooleanField(default=False, help_text='قابل فروش باشد'),
        ),
    ]
