# Generated by Django 4.2.15 on 2024-08-27 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('litner', '0008_litnerquestionmodel_hide_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestionanswercount',
            name='correct_answer_count',
        ),
        migrations.RemoveField(
            model_name='userquestionanswercount',
            name='is_hide',
        ),
        migrations.AddField(
            model_name='userquestionanswercount',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userquestionanswercount',
            name='is_correctt',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='litnermodel',
            name='paid_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='paid_litner', to=settings.AUTH_USER_MODEL, verbose_name='دسترسی کاربران'),
        ),
        migrations.DeleteModel(
            name='NotificationModel',
        ),
    ]
