# Generated by Django 4.2.15 on 2024-08-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litner', '0009_remove_userquestionanswercount_correct_answer_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='litnerkarnamedbmodel',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
