# Generated by Django 5.2 on 2025-04-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litner', '0009_lintermodel_is_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lintermodel',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='linter_season/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='mylinterclass',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='linter_class/%Y/%m/%d'),
        ),
    ]
