# Generated by Django 5.2 on 2025-04-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litner', '0010_alter_lintermodel_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leitnerbox',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='linterflashcart',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lintermodel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='mylinterclass',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='linterflashcart',
            name='box',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
