# Generated by Django 4.2.16 on 2024-10-02 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litner', '0010_litnerkarnamedbmodel_answered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='litnerkarnamemodel',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 2, 17, 27, 43, 968774, tzinfo=datetime.timezone.utc), null=True, verbose_name='کامل شده در'),
        ),
    ]
