# Generated by Django 4.2.16 on 2024-10-04 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litner', '0011_litnerkarnamemodel_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litnerkarnamemodel',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 4, 10, 51, 34, 626489, tzinfo=datetime.timezone.utc), null=True, verbose_name='کامل شده در'),
        ),
    ]
