# Generated by Django 5.2 on 2025-04-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litner', '0011_remove_leitnerbox_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linterflashcart',
            name='box',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
