# Generated by Django 4.2.16 on 2024-10-17 16:22

from django.db import migrations, models
import litner.models


class Migration(migrations.Migration):

    dependencies = [
        ('litner', '0012_alter_litnerkarnamemodel_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litnerkarnamemodel',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=litner.models.current_time, null=True, verbose_name='کامل شده در'),
        ),
    ]
