# Generated by Django 5.2 on 2025-04-30 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litner', '0012_alter_linterflashcart_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='linterflashcart',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linter_flash_cart', to='litner.lintermodel'),
        ),
    ]
