# Generated by Django 5.2 on 2025-05-01 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litner', '0013_linterflashcart_season'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='flash_cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linter_flash_cart', to='litner.linterflashcart'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='box',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='box_number',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user',
        ),
    ]
