# Generated by Django 4.2.16 on 2024-10-20 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litner', '0013_alter_litnerkarnamemodel_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litneranswer',
            name='karname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litner_azmon', to='litner.litnerkarnamemodel', verbose_name='کارنامه'),
        ),
    ]
