# Generated by Django 4.2.16 on 2024-10-20 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litner', '0014_alter_litneranswer_karname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litnerkarnamedbmodel',
            name='karname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karname', to='litner.litnerkarnamemodel'),
        ),
        migrations.AlterField(
            model_name='litnerkarnamedbmodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_id', to='litner.litnerquestionmodel'),
        ),
        migrations.AlterField(
            model_name='userquestionanswercount',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='litner.litnerquestionmodel', verbose_name='سوال'),
        ),
    ]
