# Generated by Django 5.2 on 2025-05-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litner', '0015_useranswer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='current_box_distribution',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='last_activity',
        ),
    ]
