# Generated by Django 4.2.20 on 2025-03-23 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("litner", "0015_alter_litnerkarnamedbmodel_karname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="litnermodel",
            name="paid_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="paid_litner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="دسترسی کاربران",
            ),
        ),
    ]
