# Generated by Django 5.2 on 2025-05-04 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litner', '0017_alter_leitnerbox_linter_alter_linterflashcart_season_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leitnerbox',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='leitnerbox',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='linterflashcart',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='linterflashcart',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='leitnerbox',
            name='linter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linter_box', to='litner.lintermodel', verbose_name='فصل'),
        ),
        migrations.AlterField(
            model_name='linterflashcart',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linter_flash_cart', to='litner.lintermodel'),
        ),
        migrations.AlterField(
            model_name='lintermodel',
            name='myclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linter', to='litner.mylinterclass', verbose_name='کلاس مربوطه'),
        ),
        migrations.AlterField(
            model_name='mylinterclass',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='flash_cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linter_flash_cart', to='litner.linterflashcart'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='linter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='litner.lintermodel'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leitner_progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
