# Generated by Django 5.2 on 2025-05-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litner', '0019_alter_mylinterclass_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lintermodel',
            name='is_sale',
            field=models.BooleanField(default=True, help_text='قابل فروش باشد'),
        ),
    ]
