# Generated by Django 5.2 on 2025-05-09 23:02

import django.db.models.deletion
import utils.vlaidations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField(verbose_name='متن انتخاب')),
                ('is_correct', models.BooleanField(default=False, verbose_name='صحیح بون')),
            ],
            options={
                'verbose_name': 'گزینه',
                'verbose_name_plural': 'گزینه ها',
            },
        ),
        migrations.CreateModel(
            name='ExamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='عنوان')),
                ('cover_image', models.ImageField(upload_to='media/exam_image_cover/', validators=[utils.vlaidations.validate_image_size], verbose_name='عکس کاور')),
                ('data_created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصل ها',
            },
        ),
        migrations.CreateModel(
            name='KarNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_id', to='exam.exammodel', verbose_name='امتحان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کارنامه',
                'verbose_name_plural': 'کارنامه ها',
            },
        ),
        migrations.CreateModel(
            name='MyExamClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='عنوان')),
                ('study_field', models.CharField(max_length=100, verbose_name='فیلد مطالعه')),
                ('cover_image', models.ImageField(null=True, upload_to='media/classes_image_cover/', validators=[utils.vlaidations.validate_image_size], verbose_name='عکس کاور')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس ها',
            },
        ),
        migrations.AddField(
            model_name='exammodel',
            name='myclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exam.myexamclass', verbose_name='کلاس'),
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='متن سوال')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.exammodel', verbose_name='امتحان')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
            },
        ),
        migrations.CreateModel(
            name='KarNameDBModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='choice_id', to='exam.choicemodel', verbose_name='انتخاب')),
                ('karname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='karname', to='exam.karnamemodel', verbose_name='کارنامه')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_id', to='exam.questionmodel', verbose_name='سوال')),
            ],
        ),
        migrations.AddField(
            model_name='choicemodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exam.questionmodel', verbose_name='سوال'),
        ),
    ]
