# Generated by Django 4.2.4 on 2023-12-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicemodel',
            name='choice_text',
            field=models.TextField(),
        ),
    ]
