# Generated by Django 4.2.3 on 2023-08-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammodel',
            name='is_open',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
