# Generated by Django 4.2.1 on 2023-06-07 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketHubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(null=True, upload_to='litner_image_cover/')),
                ('price', models.SmallIntegerField()),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_access', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketHubQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=150)),
                ('answers_text', models.CharField(max_length=100)),
                ('litner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litner', to='markethub.markethubmodel')),
            ],
        ),
        migrations.AddField(
            model_name='markethubmodel',
            name='paid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markethub.payment'),
        ),
        migrations.AddField(
            model_name='markethubmodel',
            name='paid_users',
            field=models.ManyToManyField(blank=True, related_name='paid_market_hubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
