# Generated by Django 4.2.3 on 2023-07-25 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketHubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(null=True, upload_to='media/litner_image_cover/')),
                ('price', models.SmallIntegerField()),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('paid_users', models.ManyToManyField(blank=True, related_name='paid_market_hubs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_access', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('MarketHub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markethub.markethubmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketHubQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=150)),
                ('answers_text', models.CharField(max_length=100)),
                ('markethub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markethub', to='markethub.markethubmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MarketHubKarNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_id', to='markethub.markethubmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketHubKarNameDBModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(null=True)),
                ('karname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='karname', to='markethub.markethubkarnamemodel')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_id', to='markethub.markethubquestionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MarketHubAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('karname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='litner_azmon', to='markethub.markethubkarnamemodel')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='markethub.markethubquestionmodel')),
            ],
        ),
    ]
