# Generated by Django 4.2.1 on 2023-06-11 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markethub', '0002_alter_payment_markethub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='MarketHub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markethub.markethubmodel'),
        ),
    ]
