# Generated by Django 4.2.4 on 2023-10-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markethub', '0002_alter_markethubmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markethubmodel',
            name='price',
            field=models.IntegerField(max_length=100000000),
        ),
    ]
