# Generated by Django 4.2.4 on 2023-12-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markethub', '0004_alter_markethubmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markethubmodel',
            name='price',
            field=models.SmallIntegerField(),
        ),
    ]
