# Generated by Django 5.2 on 2025-05-06 09:48

import catalog_app.models
import django.db.models.deletion
import utils.vlaidations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text='عنوان توصیفی برای تصویر (ضروری)', max_length=200, verbose_name='عنوان تصویر')),
                ('image_file', models.ImageField(height_field='image_height', help_text='فرمت\u200cهای پشتیبانی: JPG, PNG, WebP', upload_to=catalog_app.models.image_upload_path, validators=[utils.vlaidations.validate_image_size], verbose_name='فایل تصویر', width_field='image_width')),
                ('image_width', models.PositiveIntegerField(editable=False, null=True)),
                ('image_height', models.PositiveIntegerField(editable=False, null=True)),
                ('image_url', models.CharField(editable=False, max_length=255, null=True)),
                ('caption', models.TextField(blank=True, help_text='توضیح اختیاری درباره تصویر', verbose_name='توضیح تصویر')),
                ('file_size', models.PositiveIntegerField(editable=False, null=True, verbose_name='حجم فایل (بایت)')),
                ('file_format', models.CharField(editable=False, max_length=10, verbose_name='فرمت فایل')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_upload_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
                'ordering': ('-created_at',),
            },
        ),
    ]
