# Generated by Django 5.2 on 2025-04-25 12:25

import catalog_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=None, editable=False, null=True)),
                ('title', models.CharField(help_text='عنوان توصیفی برای تصویر (ضروری)', max_length=200, verbose_name='عنوان تصویر')),
                ('image_file', models.ImageField(height_field='image_height', help_text='فرمت\u200cهای پشتیبانی: JPG, PNG, WebP', upload_to=catalog_app.models.image_upload_path, verbose_name='فایل تصویر', width_field='image_width')),
                ('image_width', models.PositiveIntegerField(editable=False, null=True)),
                ('image_height', models.PositiveIntegerField(editable=False, null=True)),
                ('caption', models.TextField(blank=True, help_text='توضیح اختیاری درباره تصویر', verbose_name='توضیح تصویر')),
                ('file_size', models.PositiveIntegerField(editable=False, null=True, verbose_name='حجم فایل (بایت)')),
                ('file_format', models.CharField(editable=False, max_length=10, verbose_name='فرمت فایل')),
                ('is_active', models.BooleanField(default=True, help_text='نمایش/عدم نمایش تصویر در سایت', verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
                'ordering': ('-created_at',),
            },
        ),
    ]
