# Generated by Django 5.2 on 2025-05-07 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file_size',
            field=models.PositiveIntegerField(editable=False, null=True, verbose_name='حجم فایل به صورت بایت'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_height',
            field=models.PositiveIntegerField(editable=False, null=True, verbose_name='ارتفاع تصویر'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.CharField(editable=False, max_length=255, null=True, verbose_name='ادرس عکس'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_width',
            field=models.PositiveIntegerField(editable=False, null=True, verbose_name='عرض تصویر'),
        ),
        migrations.AlterField(
            model_name='image',
            name='is_deleted',
            field=models.BooleanField(blank=True, editable=False, null=True, verbose_name='حذف شده یا خیر'),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='اخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_upload_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
