# Generated by Django 5.2 on 2025-04-25 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0002_useruploadimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_upload_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserUploadImage',
        ),
    ]
