# Generated by Django 5.2 on 2025-04-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0003_image_user_delete_useruploadimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='is_active',
        ),
    ]
