# Generated by Django 5.2 on 2025-04-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0004_remove_image_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
