# Generated by Django 5.2 on 2025-04-25 17:37

import catalog_app.models
import utils.vlaidations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0005_image_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(height_field='image_height', help_text='فرمت\u200cهای پشتیبانی: JPG, PNG, WebP', upload_to=catalog_app.models.image_upload_path, validators=[utils.vlaidations.validate_image_size], verbose_name='فایل تصویر', width_field='image_width'),
        ),
    ]
